In [20]:
# importing all necessary modules
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
# Loading data into pandas dataframe.
file_location = '../data/complaints.csv.zip'

full_df = pd.read_csv(file_location)

In [3]:
# First few lines of dataframe
full_df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,2019-09-24,Debt collection,I do not know,Attempts to collect debt not owed,Debt is not yours,transworld systems inc. \nis trying to collect...,NaN,TRANSWORLD SYSTEMS INC,FL,335XX,NaN,Consent provided,Web,2019-09-24,Closed with explanation,Yes,NaN,3384392
1,2019-09-19,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,PA,15206,NaN,Consent not provided,Web,2019-09-20,Closed with non-monetary relief,Yes,NaN,3379500
2,2019-11-08,Debt collection,I do not know,Communication tactics,Frequent or repeated calls,"Over the past 2 weeks, I have been receiving e...",NaN,"Diversified Consultants, Inc.",NC,275XX,NaN,Consent provided,Web,2019-11-08,Closed with explanation,Yes,NaN,3433198
3,2019-09-15,Debt collection,Other debt,Attempts to collect debt not owed,Debt was result of identity theft,Pioneer has committed several federal violatio...,NaN,Pioneer Capital Solutions Inc,CA,925XX,NaN,Consent provided,Web,2019-09-15,Closed with explanation,Yes,NaN,3374555
4,2020-10-23,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,FL,334XX,NaN,Other,Web,2020-10-23,Closed with explanation,Yes,NaN,3915909

In [4]:
# Shape of the data
full_df.shape

(1839405, 18)

In [5]:
# Display All columns
full_df.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Consumer consent provided?',
       'Submitted via', 'Date sent to company', 'Company response to consumer',
       'Timely response?', 'Consumer disputed?', 'Complaint ID'],
      dtype='object')

In [6]:
# Display information about the columns
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1839405 entries, 0 to 1839404
Data columns (total 18 columns):
 #   Column                        Dtype
---  ------                        -----
 0   Date received                 object
 1   Product                       object
 2   Sub-product                   object
 3   Issue                         object
 4   Sub-issue                     object
 5   Consumer complaint narrative  object
 6   Company public response       object
 7   Company                       object
 8   State                         object
 9   ZIP code                      object
 10  Tags                          object
 11  Consumer consent provided?    object
 12  Submitted via                 object
 13  Date sent to company          object
 14  Company response to consumer  object
 15  Timely response?              object
 16  Consumer disputed?            object
 17  Complaint ID                  int64
dtypes: int64(1), object(17)
memory usage: 252.6+ MB

In [7]:
# Select only necessary columns for further processing.
necessary_columns = ['Product', 'Sub-product', 'Issue',
                     'Sub-issue', 'Consumer complaint narrative', 'State',
                      'Tags', 'Submitted via', 'Timely response?']

In [8]:
# create new dataframe with necessary columns
df = full_df[necessary_columns]

In [9]:
# Changing column Name
df.columns = ['label', 'sub_label','issue',
              'sub-issue', 'full_text', 'state',
              'tags', 'submitted_via', 'response']

In [10]:
df.head()

,label,sub_label,issue,sub-issue,full_text,state,tags,submitted_via,response
0,Debt collection,I do not know,Attempts to collect debt not owed,Debt is not yours,transworld systems inc. \nis trying to collect...,FL,NaN,Web,Yes
1,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,PA,NaN,Web,Yes
2,Debt collection,I do not know,Communication tactics,Frequent or repeated calls,"Over the past 2 weeks, I have been receiving e...",NC,NaN,Web,Yes
3,Debt collection,Other debt,Attempts to collect debt not owed,Debt was result of identity theft,Pioneer has committed several federal violatio...,CA,NaN,Web,Yes
4,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,FL,NaN,Web,Yes

In [11]:
# Checking Null values in the frame
df.isnull().sum()

label                  0
sub_label         235165
issue                  0
sub-issue         589910
full_text        1214191
state              34551
tags             1598292
submitted_via          0
response               0
dtype: int64

In [12]:
# Checking How many values in label column
df['label'].value_counts().to_frame()

                                                     label
Credit reporting, credit repair services, or ot...  553660
Debt collection                                     321220
Mortgage                                            314233
Credit reporting                                    140432
Credit card or prepaid card                          94142
Credit card                                          89190
Bank account or service                              86206
Checking or savings account                          76192
Student loan                                         59729
Consumer Loan                                        31604
Vehicle loan or lease                                20876
Money transfer, virtual currency, or money service   20786
Payday loan, title loan, or personal loan            15342
Payday loan                                           5543
Money transfers                                       5354
Prepaid card                                          3819
Other financial service                               1059
Virtual currency                                        18

In [13]:
# Set pandas option to show all column since notebook
# Restriction on showing all columns
pd.set_option('display.max_rows', None)

In [14]:
# Checking How many values in sub-label column
df['sub_label'].value_counts().to_frame()

                                            sub_label
Credit reporting                               546054
Checking account                               117190
Other mortgage                                  86635
General-purpose credit card or charge card      71028
Conventional fixed mortgage                     70613
I do not know                                   67782
Conventional home mortgage                      51861
Other debt                                      50883
Other (i.e. phone, health club, etc.)           44543
Credit card debt                                38730
FHA mortgage                                    37041
Credit card                                     28698
Federal student loan servicing                  27896
Medical debt                                    27858
Conventional adjustable mortgage (ARM)          25380
Non-federal student loan                        25164
Medical                                         21186
Other bank product/service                      17825
Vehicle loan                                    17782
Loan                                            17385
Installment loan                                15052
Store credit card                               14825
Payday loan                                     11964
Home equity loan or line of credit              11624
Other type of mortgage                          11396
Other banking product or service                10623
Savings account                                 10504
VA mortgage                                     10064
Private student loan                             9550
Domestic (US) money transfer                     8609
International money transfer                     6171
Other personal consumer report                   6045
Mobile or digital wallet                         6020
Auto debt                                        5810
Home equity loan or line of credit (HELOC)       5623
Payday loan debt                                 5325
Personal line of credit                          5051
Mortgage                                         4809
Government benefit card                          3847
Mortgage debt                                    3755
Auto                                             3755
General-purpose prepaid card                     3706
Lease                                            3473
(CD) Certificate of deposit                      3417
Reverse mortgage                                 3335
Virtual currency                                 3327
Federal student loan debt                        2666
Vehicle lease                                    2658
Private student loan debt                        2502
Federal student loan                             2475
CD (Certificate of Deposit)                      2166
Title loan                                       1934
General purpose card                             1752
Credit repair services                           1560
Debt settlement                                   828
Payroll card                                      802
Second mortgage                                   662
Cashing a check without an account                625
Money order                                       519
Mobile wallet                                     418
Gift or merchant card                             402
Traveler's check or cashier's check               398
Government benefit payment card                   389
Gift card                                         334
Check cashing service                             333
Foreign currency exchange                         290
Check cashing                                     266
Refund anticipation check                         265
ID prepaid card                                   207
Other special purpose card                        191
Pawn loan                                         133
Credit repair                                     103
Traveler’s/Cashier’s checks                        88
Transit card                                       37
Electronic Benefit Transfer / EBT card             12
Student prepaid card                               11

In [15]:
# How many values on tags column
df['tags'].value_counts().to_frame()

                                 tags
Servicemember                  126278
Older American                  94847
Older American, Servicemember   19988

In [16]:
# check values in submitted column
df['submitted_via'].value_counts().to_frame()

             submitted_via
Web                1429188
Referral            202707
Phone               105169
Postal mail          78639
Fax                  23279
Email                  423

In [17]:
# Check values in response column
df['response'].value_counts().to_frame()

     response
Yes   1800501
No      38904

In [ ]:
# Retrive full_text based on customer submission
# This is to check null values.

df[df['submitted_via'] == 'Web'].sum()